# The Rio de Janeiro practice-based research network database - real world information to study primary care and family medicine. 

## Introduction:   



For the last 40 years, many advances in Primary Health Care (PHC) were made due to the momentum created by the Alma-Ata declaration35. Many countries have achieved good results in creating and developing universal, accessible, and cost-effective PHC systems25,107. The principles stated in 1978 in Alma-Ata were reinforced in 2018 by the Astana declaration108, pointing the importance of having a strong PHC as a strong element of social development to achieve social justice and good health.    

With short and strong sentences, these documents state that health disparities will only be overcome through strong PHC built in a spirit of social justice relying on health workers that are “suitably trained socially and technically to work as a health team” and to “respond to the expressed health needs of the community”35. The big picture is clear, but having a closer look at the terms “health workers” and “health teams” we cannot find any specification about what should be the health workers in PHC or how a health team must be assembled. Many times family physicians (FP) use the terms PHC and Family Medicine (FM) interchangeably – maybe because they work in primary care, maybe because they see themselves as the specialists in primary care – but in those documents FM is never mentioned as the medical specialty  for primary care.   

Only at the World Health Report 200839 the World Health Organization mention FM referring to the fact that PHC has been studied extensively in high income countries where physicians with specialization in FM working in PC is the norm. This is a very important fact related to the development of PHC – and FM – around the world. In many low and middle income countries (LMIC) FM is not even a medical specialty10 and, when it is present, the role FP play as health care providers can vary largely depending on the health system109. The lack of a globally accepted definition is a consequence of the incipiency of the specialty in LMIC110. For those countries the question of proving the value of having a strong PHC system for policymakers and health managers is part of the daily struggle for sustainability - the same can be said about FM.    

Studies looking at the impact of PHC often miss this important element involved in delivering care for the patients, that is the medical professional. In Brazil, a country with a large universal public health care system111 and a successful history of development of community-based primary care15, studies about its impact have proven substantial effects on reducing infant and neonatal mortality112, hospital admissions related to ambulatory-care sensitive conditions113 and cardiovascular deaths22, but also fail to address the impact of the medical specialty.    

Under the national Programa de Saúde da Família (Family Health Program - FHP) launched in 1994, Family Health Teams (FHT) composed by one doctor, one nurse and four to six community health agents provide care for 4,000 people in a catchment area. Today, 64% of the Brazilian population is covered by the 43,000 FHT active in the programe19, but only a few of those teams have a trained family physician as the doctor in charge. Despite recent policies that have tried to boost28,114 the creation and growth of residency programs in FM, only 4.4% of the residency training seats are dedicated to FM. With only 5,500 FP in the country6 (1.4% of all specialists; not all of them with residency training), FM is still not seen by policymakers and health managers as a necessary medical specialty to be a health care provider in PHC.    

One recent exception was the PHC reform experienced in Rio de Janeiro from 2008 until 2016, when the coverage of the PSF increased from 3.5% to almost 70% and investments were made to create a new FM training program in 2012 (and expand the two programs already stablished) as a capacity building initiative for human resources115. 206 seats are offered every year for doctors who want to become FP. They attend a two-year program with a workload of 55 hours per week, 90% of them in community-based primary care clinics, with a strong emphasis in clinical reasoning, communication skills, patient-centered care, multimorbidity and patients’ complexity, evidence-based medicine, quality improvement activities, research in PC, training of small procedures, care of vulnerable and neglected populations and clinical content about the most prevalent conditions in primary care116. They receive monthly a standard scholarship for two years from the ministry of health (R\$ 3,300.00 or US\$ 820 - same for every resident in Brazil), and an extra scholarship (R\$ 7,000.00 or US\$ 1,740) from the  municipality, as a financial incentive for provision and fixation. Preceptors (trainers) also receive a financial incentive for being responsible for supervising two to four residents31.    


Today Rio de Janeiro alone is responsible for almost 20% of the FM training seats in the country and almost 85% of the graduted  students end up working at the public PHC system in Rio de Janeiro. This initiative created a natural experiment in the city, where some FHT have a FP as the doctor in charge, others have doctors with only a medical degree and no residency training (generalists). A perfect setting for studies about the effect of family medicine training on patient care in PHC.    


The Rio de Janeiro practice-based research neetwork (RioPBRN) is the novice research unit created by the Family and Community Medicine Residency Program at the Rio de Janeiro Health Department. Nowadays it has been building a data-warehouse compiling information related to primary care in Rio de Janeiro that will serve as data source for researchers interested on PHC subjects, such as training in FM and capacity building of human resources, PHC in LMIC, health care systems development, cost-effectiveness analysis, community-based primary care and team-based work. This article aims to present the structure of this dataset and the story behind the process of building it.

