# Quick references {-}    



## Primary Care {-}

- **The world health report 2008** [Primary Health Care - now more than ever.](https://www.who.int/whr/2008/whr08_en.pdf){target="_blank"}    


- **Contribution of Primary Care to Health Systems and Health** [Barbara Starfield, Leiyu Shi, and James Macinko; Milbank Q. 2005 Sep; 83(3): 457–502. doi: 10.1111/j.1468-0009.2005.00409.x](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2690145/){target="_blank"}    



- **The Structure of Primary Care: Framing a Big Picture** [James M. Gill; (Fam Med 2004;36(1):65-8.)](https://fammedarchives.blob.core.windows.net/imagesandpdfs/fmhub/fm2004/January/James65.pdf){target="_blank"}     

- **Evidence and primary care** - Primary care is the subject of more charters, declarations, manifestos, and principles than any other medical discipline, except perhaps its similarly plagued cousin, public health.The force of the argument for specialisation, on pragmatic grounds alone, seems irresistible. Has “evidence-based medicine” made primary care by generalist doctors an anachronism? General-practice research is too often about administration. A creeping managerialism is destroying one of primary care’s most important distinguishing traits—namely, the flexibility, informality, and pastoral strengths that come with a degree of laxity in its organisation. [Horton, R. (1999). Evidence and primary care. The Lancet, 353(9153), 609–610. doi:10.1016/s0140-6736(99)00056-2](https://sci-hub.se/https://doi.org/10.1016/S0140-6736(99)00056-2){target="_blank"}  


- **The content and methodology of research papers published in three United Kingdom primary care journals.** Nearly half of published studies in UK primary care journals were concerned with either organization and administration issues in primary care or social problems (509 studies, 48%). Just over half were either qualitative studies or surveys of opinion or attitudes (528 studies, 50%). The overall number of RCTs was low (67 studies, 6%), and the proportion published has not changed over time (chi 2 for trend = 3.79, df = 1, P = 0.051). In contrast to surgical journals, nearly one-fifth of studies in general practice followed a longitudinal design (186 studies, 18%). [The content and methodology of research papers published in three United Kingdom primary care journals. TOBY THOMAS, TOM FAHEY, MAGGIE SOMERSET; British Journal of General Practice, May 1998](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1410169/pdf/brjgenprac00086-0019.pdf){target="_blank"}   


- **30 years after Alma-Ata: has primary health care worked in countries?** [Jon Rohde, Simon Cousens, Mickey Chopra, Viroj Tangcharoensathien, Robert Black, Zulfi qar A Bhutta, Joy E Lawn;  The Lancet; Vol 372 September 13, 2008](https://sci-hub.se/https://doi.org/10.1016/S0140-6736(08)61405-1){target="_blank"}    


- **Alma-Ata at 40 years: reflections from the Lancet Commission on Investing in Health** [David A Watkins, Gavin Yamey, Marco Schäferhoff, Olusoji Adeyi, George Alleyne, Ala Alwan, Seth Berkley, Richard Feachem, Julio Frenk, Gargee Ghosh, Sue J Goldie, Yan Guo, Sanjeev Gupta, Felicia Knaul, Margaret Kruk, Rachel Nugent, Osondu Ogbuoji, Jinyuan Qi, Srinath Reddy, Helen Saxenian, Agnés Soucat, Dean T Jamison, Lawrence H Summers](https://sci-hub.se/https://doi.org/10.1016/S0140-6736(18)32389-4){target="_blank"}    


- **Universal Coverage Scheme Assessment of the first 10 years in Thailand** [Asia Pacific Journal of Family Medicine, 5 (1), Yongyuth PONGSUPAP and Wim VAN LERBERGHE](https://www.hsri.or.th/sites/default/files/browse/tor5-1-1.pdf){target="_blank"}    

- **Patient experience with self-styled family practices and conventional primary care in Thailand** The self-styled family practices have advantages in all domains of responsiveness when compared to public hospital OPDs. Attention was perceived to be more prompt in private clinics and private hospitals, but for the other domains, self-styled family practices provided greater patient satisfaction. Self-styled family practices and public hospitals were felt to be trusted more than private clinics and hospitals. [Asia Pacific Journal of Family Medicine, 5 (1), Yongyuth PONGSUPAP and Wim VAN LERBERGHE](http://www.apfmj-archive.com/afm5_1/afm27.pdf){target="_blank"}     




## Evidences about PHC in Brazil {-}   


- **Major Expansion Of Primary Care In Brazil Linked To Decline In Unnecessary Hospitalization.** During 1999–2007, hospitalizations in Brazil for ambulatory care–sensitive chronic diseases, including cardiovascular disease, stroke, and asthma, fell at a rate that was statistically significant and almost twice the rate of decline in hospitalizations for all other causes. In municipalities with high Family Health Program enrollment, chronic disease hospitalization rates were 13 percent lower than in municipalities with low enrollment, when other factors were held constant. [James Macinko, Inês Dourado, Rosana Aquino, Palmira de Fátima Bonolo, Maria Fernanda Lima-Costa, Maria Guadalupe Medina, Eduardo Mota, Veneza Berenice de Oliveira, and Maria Aparecida Turci; HEALTH AFFAIRS VOL. 29, NO. 12](https://www.healthaffairs.org/doi/full/10.1377/hlthaff.2010.0251){target="_blank"}     



- **Impact of the Family Health Program on Infant Mortality in Brazilian Municipalities.** We observed a statistically significant negative association between FHP coverage and infant mortality rate. After we controlled for potential confounders, the reduction in the infant mortality rate was 13.0%, 16.0%, and 22.0%, respectively for the 3 levels of FHP coverage. The effect of the FHP was greater in municipalities with a higher infant mortality rate and lower human development index at the beginning of the study period. [Rosana Aquino, Nelson F. de Oliveira, and Mauricio L. Barreto; anuary 2009, Vol 99, No. 1 | American Journal of Public Health](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2636620/pdf/87.pdf){target="_blank"}    


- **Large reductions in amenable mortality associated with Brazil’s Primary Care expansion and strong health governance.** [Health Affairs, 36(1), 149–158. Hone, T., Rasella, D., Barreto, M., Atun, R., Majeed, A., & Millett, C. (2017). doi:10.1377/hlthaff.2016.0966 ](https://www.healthaffairs.org/doi/full/10.1377/hlthaff.2016.0966?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%3dpubmed){target="_blank"}   


- **Analysis of prehospital care for stroke and acute myocardial infarction in the elderly population of Minas Gerais, Brazil.** Statistically significant associations were found between indicators of ESF coverage and presence of SAMU with indicators of stroke and AMI mortality, for both sexes, except for male AMI. [Rev Assoc Med Bras 2010; 56(4): 452-7](http://www.scielo.br/pdf/ramb/v56n4/en_19.pdf){target="_blank"}     


- **Estratégia Saúde da Família em comparação a outras fontes de atenção: indicadores de uso e qualidade dos serviços de saúde em Belo Horizonte, Minas Gerais, Brasil** A recomendação para outra pessoa dos serviços de saúde utilizados foi mais frequente entre usuários regulares da ESF (61,9%) e afiliados a plano privado (55,6%), em comparação à UBS (45,4%). [Cad. Saúde Pública vol.29 no.7 Rio de Janeiro July 2013](http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0102-311X2013000700011&lng=en&nrm=iso&tlng=en){target="_blank"}     



- **Impact of primary health care on mortality from heart and cerebrovascular diseases in Brazil: a nationwide analysis of longitudinal data.** FHP coverage was negatively associated with mortality rates from cerebrovascular and heart diseases (ambulatory care-sensitive conditions) in both unadjusted and adjusted models for demographic, social, and economic confounders. The FHP had no effect on the mortality rate for accidents, used as a control. The rate ratio for the effect of consolidated annual FHP coverage on cerebrovascular disease mortality and on heart disease mortality was 0.82 (95% confidence interval 0.79 to 0.86) and 0.79 (0.75 to 0.80) respectively, reaching the value of 0.69 (0.66 to 0.73) and 0.64 (0.59 to 0.68) when the coverage was consolidated during all the previous eight years. Moreover, FHP coverage increased the number of health education activities, domiciliary visits, and medical consultations and reduced hospitalisation rates for cerebrovascular and heart disease. Several complementary analyses showed quantitatively similar results. [Davide Rasella , Michael O Harhay, Marina L Pamponet, Rosana Aquino, Mauricio L Barreto; BMJ 2014;348:g4014 doi: 10.1136/bmj.g4014](https://www.bmj.com/content/bmj/349/bmj.g4014.full.pdf){target="_blank"}    


- **Impact of the Family Health Program on the quality of vital information and reduction of child unattended deaths in Brazil: an ecological longitudinal study.** A statistically significant negative association was observed between PSF coverage levels, classified in none (0%, the reference category), low (<30.0%), intermediate (≥ 30.0% and <70.0%) and high (≥ 70.0%), and all analysed mortalities rates, with a reduction of 17% (Rate Ratio [RR]: 0.83; 95% confidence interval [CI]: 0.79 - 0.88), 35% (RR: 0.65; 95% CI: 0.61-0.68) and 50% (RR: 0.50; 95% CI: 0.47-0.53) on under-five mortality due to ill-defined causes, respectively. In the mortality rate for unattended death the reduction was even greater, reaching 60% (RR: 0.40; 95% CI: 0.37-0.44) in the municipalities with the highest PSF coverage. The PSF effect on unattended deaths was slightly stronger in municipalities with a higher human development index. [Rasella et al. BMC Public Health 2010, 10:380](https://bmcpublichealth.biomedcentral.com/track/pdf/10.1186/1471-2458-10-380){target="_blank"}    


- **Reducing Childhood Mortality From Diarrhea and Lower Respiratory Tract Infections in Brazil.** A statistically significant negative association was observed between FHP coverage levels, classified as none (the reference category), low (30%), intermediate (30% and 70%), or high (70%), and all analyzed mortality rates, with a reduction of 4% (95% confidence interval [CI]: 2%– 6%), 9% (95% CI: 7%–12%), and 13% (95% CI: 10%–15%), respectively, on mortality rates or children younger than 5. The greatest effect was on postneonatal mortality. Reductions of 31% (95% CI: 20%– 40%) and 19% (95% CI: 8%–28%) in mortality rates from diarrheal diseases and lower respiratory infections, respectively, were found in the group of municipalities with the highest FHP coverage [Rasella, D., Aquino, R., & Barreto, M. L. (2010). PEDIATRICS, 126(3), e534–e540. doi:10.1542/peds.2009-3197](https://sci-hub.tw/10.1542/peds.2009-3197){target="_blank"}    




- **Public primary health care and children’s health in Brazil: evidence from siblings.** The results indicate that children for whom the Family Health Program was available in their municipalities during the prenatal period are healthier than children for whom the program was not available during the same period of their lives. [Maurício Reis, J Popul Econ (2014) 27:421–445, DOI 10.1007/s00148-013-0482-8](https://sci-hub.tw/10.1007/s00148-013-0482-8){target="_blank"}    


- **Evaluating the impact of community-based health interventions: evidence from Brazil's Family Health Program.** We find consistent effects of the program on reductions in mortality throughout the age distribution, but mainly at earlier ages. Municipalities in the poorest regions of the country benefit particularly from the program. For these regions, implementation of the program is also robustly associated with increased labor supply of adults, reduced fertility, and increased school enrollment. Evidence suggests that the Family Health Program is a highly cost-effective tool for improving health in poor areas [ROMERO ROCHA, RODRIGO R. SOARES, Health Econ. 19: 126–158 (2010), DOI: 10.1002/hec.1607](https://sci-hub.tw/10.1002/hec.1607){target="_blank"}    


- **Diferenças no processo de atenção ao pré-natal entre unidades da Estratégia Saúde da Família e unidades tradicionais em um município da Região Sul do Brasil.** Dentre as 961 grávidas, as da ESF receberam em maior percentual alguns cuidados (uso de sulfato ferroso, vacina antitetânica, número de exames para HIV e sífilis). Outros procedimentos foram mais frequentes na ESF, mas estavam abaixo do valor recomendado (exame das mamas e prevenção do câncer cervical). As medidas de pressão arterial, altura uterina e de peso foram muito frequentes nos dois grupos. A identificação de gestantes no primeiro trimestre não alcançou 70%. [Raul A. Mendoza-Sassi; Juraci Almeida Cesar; Tarso Pereira Teixeira; César Ravache; Gerson Donizete Araújo; Tatiana Corrêa da Silva; Cad. Saúde Pública vol.27 no.4 Rio de Janeiro Apr. 2011](http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0102-311X2011000400018){target="_blank"}    


- **Time trend of Family Health Strategy coverage in Brazil, its Regions and Federative Units, 2006-2016.** FHS coverage in Brazil in 2006 and 2016 was 45.3% and 64.0%, respectively, with an increasing trend of coverage (annual variation = 8.4%: 95%CI 7.4;9.3); all five regions showed an increasing trend in coverage, as did the majority of FUs, with the exception of Roraima, Amapá, Piauí, Rio Grande do Norte and Paraíba, which showed stability; in 2016, 14 FUs had coverage of between 75 and 100%, and 11 had coverage of between 50 and 74,9%; coverage in São Paulo and the Federal District was below 50%. [Epidemiol. Serv. Saude, Brasília, 27(3):e2017170, 2018](https://www.scielosp.org/pdf/ress/2018.v27n3/e2017170/en){target="_blank"}    



## Family Medicine {-}   


- **The Besrour Papers: Seeking evidence for family medicine.** [David Ponka; Afr J Prm Health Care Fam Med. 2017;9(1), a1559. https://doi.org/10.4102/phcfm.v9i1.1559](https://phcfm.org/index.php/phcfm/article/view/1559/2228){target="_blank"}    


- **Family medicine around the world: overview by region The Besrour Papers: a series on the state of family medicine in the world.** [Neil Arya, Christine Gibson, David Ponka, Cynthia Haq, Stephanie Hansel, Bruce Dahlman, Katherine Rouleau](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5471080/pdf/0630436.pdf){target="_blank"}    

- **Provider Continuity in Family Medicine: Does It Make a Difference for Total Health Care Costs?** Bivariate analyses showed that patients who were visiting the same family physician had a lower total cost for medical care. A multivariate linear regression showed that provider continuity with a family physician was one of the most important explanatory variables related to the total health care cost. [ANNALS OF FAMILY MEDICINE VOL. 1, NO. 3 SEPTEMBER/OCTOBER 2003](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1466579/pdf/0010144.pdf){target="_blank"}    

- **Why don’t family physicians follow clinical practice guidelines for cancer screening?** 4 domains in a model of the determinants of cancer screening in primary care: physician characteristics, patient characteristics, social factors and practice characteristics. [CMAJ • OCT. 6, 1998; 159 (7)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1232738/pdf/cmaj_159_7_797.pdf){target="_blank"}    


- **A Comparison o f Family Physicians’ and Obstetricians’ Intrapartum Management of Low-Risk Pregnancies.** Olhar evidências mais novas para isso aqui - Family physicians had lower rates for induction, external and internal fetal monitoring, narcotic analgesia use, and postpartum oxytocin use. Women cared for by family physicians spent less time in the hospital, both during labor and postpartum. [The Journal of Family Practice, Vol. 37, No. 5, 1993](https://mdedge-files-live.s3.us-east-2.amazonaws.com/files/s3fs-public/jfp-archived-issues/1993-volume_36-37/JFP_1993-11_v37_i5_a-comparison-of-family-physicians-and-o.pdf){target="_blank"}    


- **Quality in general practice consultations: a qualitative study of the views of patients living in an area of high socio-economic deprivation in Scotland.** Patients' perceptions of the quality of the consultation with GPs consisted of two broad, inter-relating themes; (1) the GPs' competence, and (2) the GPs empathy or ' caring'. Competence was often assumed but many factors coloured this assumption, in particular whether patients had experienced (directly or indirectly with a close family member) 'successful' outcomes with that doctor previously or not. 'Caring' related to patients feeling (a) listened to by the doctor and being able to talk; (b) valued as an individual by the doctor (c) that the doctor understood 'the bigger picture', and (d) the doctors' explanations were clear and understandable. Relational continuity of care (being able to see the same GP and having a good relationship), and having sufficient time in the consultation were closely linked with perceptions of consultation quality. [BMC Fam Pract. 2007; 8: 22. doi: 10.1186/1471-2296-8-22](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1857696/){target="_blank"}    


- **Comparison of breast cancer patient satisfaction with follow-up in primary care versus specialist care: results from a randomized controlled trial.** The general practice group selected responses indicating greater satisfaction than did the hospital group on virtually every question. Furthermore, in the general practice group there was a significant increase in satisfaction over baseline; a similar significant increase in satisfaction over baseline was not found in the hospital group. [Br J Gen Pract. 1999 Sep; 49(446): 705–710.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1313497/){target="_blank"}    


- **The paradox of the parts and the whole in understanding and improving general practice** Quality of care measures and clinical indicators are typically criticized for the limitations of the scientific evidence on which they are based and for their strong reliance on what can be measured. This larger issue is the problem of the parts and the whole - that is, indicators of the quality of care for specific diseases may not adequately represent the quality of care for the whole person. This is a particular issue in assessing general practice, in which patients often present for care of multiple problems that span different acute and chronic illness, prevention, mental health, and family care. Illness are often non-specific and undifferentiated, and much of the quality of practice involves defining the problem to be addressed. [Kurt Stange, International Journal for Quality in Health Care](https://sci-hub.tw/10.1093/intqhc/14.4.267){target="_blank"}       

- **Specialists' perception of referrals from general doctors and family physicians working as primary care doctors in Thailand.** Referrals were judged as inappropriate more often in the GD group. For referrals to internal medicine, GDs provided more incorrect diagnoses and unreasonable referrals. For orthopaedic referrals, GDs provided more incorrect diagnoses and inadequate investigations before referral. The most common comments on inappropriate referral were non-specific diagnosis, non-comprehensive case approach, too early referral, and inadequate investigation. [Quality in primary care 14(1):41-48; February 2006](https://www.researchgate.net/publication/233627532_Specialists'_perception_of_referrals_from_general_doctors_and_family_physicians_working_as_primary_care_doctors_in_Thailand){target="_blank"}    


- **Quality of Referrals from Family Medicine to Secondary Care in a University Hospital: Communication and Continuity of Care.** About 80% of the referrals were made to 6 subspecialties: gastroenterology (21.95%), cardiology (17.18%), neurology (13.87%), pulmonology (11.59%), endocrinology (8.7%) and nephrology (7.87%). Consultations were done in 87.78% of the referrals. The mean waiting time was 18.27 days. 82.23% did not record a reason for referral and 13.22% did not make the referring problem clear. About 20 percent of referrals were made too early. Feedback from a specialist was provided in only 14.08% of cases. And only 3.73% of patients were sent back to family physicians. The retrospective review suggested that 23.6% of cases could have been managed by family physicians. [Lertrattananon, D., Thamakaison, S., Tubtimtes, S., Pumkompol, T., & Somsri, S. (1). Ramathibodi Medical Journal, 38(4), 274-283.](https://www.tci-thaijo.org/index.php/ramajournal/article/view/57463){target="_blank"}    





- **Does Family Medicine training in Thailand affect patient satisfaction with primary care doctors?** The response rate was 70%. There were significant differences in mean GPAQ scores among faculty family physicians, residents and general doctors. For continuity of care, patients gave higher scores for faculty family physicians (67.87) compared to residents (64.57) and general doctors (62.51). For communication skills, patients gave the highest GPAQ scores to faculty family physicians (69.77) and family medicine residents (69.79). For enablement, faculty family physicians received the highest score (82.44)
followed by family medicine residents (80.75) and general doctors (76.29). [Darin Jaturapatporn, Alan Dellow, BMC Family Practice 2007, 8:14 doi:10.1186/1471-2296-8-14](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1852109/pdf/1471-2296-8-14.pdf){target="_blank"}    


## Training Family Medicine {-}   

- **A formação em medicina de família no Brasil: a necessidade de caminhos convergentes.** [Armando Henrique Norman, 2014](https://www.rbmfc.org.br/rbmfc/article/view/875){target="_blank"}    



- **Quality Indicators for Primary Health Care.** Regarding raw data, lack of standardization of collection tools between projects could lead to invalid comparisons. In areas that international projects operate in parallel to national initiatives, there may be problems regarding expenses and burden of data collection, which might create competing interests and low quality of information. Regarding the domains of the indicators selected,
it was found that most indicators belonged to the “Quality/Safety” group of domains (13.85%), followed by the indicator sets of “Access/Facilities/Care Redesign” (9.89%) and “Comprehensiveness or Comprehensive care or Equipment for Comprehensive care”
(5.76%) [Simou, E., Pliatsika, P., Koutsogeorgou, E., & Roumeliotou, A. (2015). Journal of Public Health Management and Practice, 21(5), E8–E16. doi:10.1097/phh.0000000000000037](https://sci-hub.tw/10.1097/phh.0000000000000037){target="_blank"}    



## Family Medicine and Public Health {-}   

- **General practice and public health: who is my patient?** Explaining what is general practice and public health. General practitioners (GPs) tend to focus most of their energies on providing primary healthcare to individuals, with less attention to the overall population health issues in their community. In contrast, public health practitioners tend to focus on the health needs of entire populations, by addressing the social determinants of health, with less attention to individual patient care. 
[Volume 43, No.7, July 2014 Pages 483-486](https://www.racgp.org.au/afp/2014/july/who-is-my-patient/){target="_blank"}    

- **Where Have the Generalists Gone? They Became Specialists, Then Subspecialists.** [James E. Dalen, Kenneth J. Ryan, Joseph S. Alpert, The American Journal of Medicine, Vol 130, No 7, July 2017](https://www.amjmed.com/article/S0002-9343%2817%2930134-1/pdf){target="_blank"}    



## Health systems evaluation {-}

- **The Quality of Care. How Can It Be Assessed?** Avedis Donabedian, MD, MPH, (1988).  [JAMA, 260(12), 1743. doi:10.1001/jama.1988.03410120089033](https://sci-hub.tw/10.1001/jama.1988.03410120089033){target="_blank"}    



## SUS {-}   

- **The Brazilian health system at crossroads: progress, crisis and resilience.** From 2000 to 2014, total health expenditure rose from 7.0% to 8.3% of gross domestic product and population coverage with the Family Health Strategy rose from 7.6% to 58.2%. [Adriano Massuda, Thomas Hone, Fernando Antonio Gomes Leles, Marcia C de Castro, Rifat Atun; BMJ Glob Health 2018;3:e000829. doi:10.1136/bmjgh-2018-000829](https://journals.plos.org/plosmedicine/article/file?id=10.1371/journal.pmed.1001692&type=printable){target="_blank"}     


- **Monitoring and Evaluating Progress towards Universal Health Coverage in Brazil.** The chronic underfunding of the system imposes serious limitations on the overall expansion of the SUS, particularly at the secondary and tertiary levels. [Barreto ML, Rasella D, Machado DB, Aquino R, Lima D, Garcia LP, et al. (2014). PLoS Med 11(9): e1001692.](https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1001692#){target="_blank"}   


## Capacity building of Human resources {-}  

- **Attitudes, barriers, and enablers towards conducting primary care research in Banda Aceh, Indonesia: a qualitative research study.** weak research policy, lack of research funding and infrastructure, complicated research bureaucracy and administrative process, as well as time constraints for conducting research relative to other duties. Participants expressed that personal motivation was a very important enabler/facilitator for increasing research activities. In order to improve research productivity, the majority of participants suggested that having local awards and formal recognition, having the opportunity to partner with local business and communities, provision of incentives, and having access to a research help-desk would be benefcial. [Ichsan Ichsan1, Nur Wahyuniati, Ryan McKee, Louella Lobo, Karla Lancaster and Lynda Redwood‑Campbell;Asia Pac Fam Med (2018) 17:8; https://doi.org/10.1186/s12930-018-0045-y](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6064079/pdf/12930_2018_Article_45.pdf){target="_blank"}    



- **Regulação da formação de especialistas: inter-relações com o Programa Mais Médicos** Programa Nacional de Apoio à Formação de Médicos Especialistas em Áreas Estratégicas – Pró-Residência, criado em 2009. [Revista de Saúde Coletiva, Rio de Janeiro, 26(2): 633-667, 2016](http://www.scielo.br/pdf/physis/v26n2/0103-7331-physis-26-02-00633.pdf){target="_blank"}    



- **A expansão de vagas de residência de Medicina de Família e Comunidade por municípios e o Programa Mais Médicos.** [Storti MMT, Oliveira FP, Xavier AL. Interface (Botucatu). 2017; 21(Supl.1):1301-13.](http://www.scielo.br/pdf/icse/v21s1/1807-5762-icse-21-s1-1301.pdf){target="_blank"}    


- **Formação de Médicos Especialistas no SUS: Descrição e Análise da Implementação do Programa Nacional de Apoio à Formação de Médicos Especialistas em Áreas Estratégicas (Pró-Residência).** [Revista Brasileira de Educação Médica, 2013](http://www.scielo.br/pdf/rbem/v37n1/11.pdf){target="_blank"}    



- **The More Doctors Program and the rearrangement of medical residency education focused on Family and Community Medicine.** [Felipe Proenço de Oliveira, Cássia de Andrade Araújo, Odete Messa Torres, Alexandre Medeiros de Figueiredo, Priscilla Azevedo Souza, Francisco Arsego de Oliveira;  Interface (Botucatu). 2019; 23(1): e180008 https://doi.org/10.1590/Interface.180008](http://www.scielo.br/pdf/icse/v23s1/1807-5762-icse-23-s1-e180008.pdf){target="_blank"}   


## Ambulatory-care sensitive conditions {-}

- **Impact Of Socioeconomic Status On Hospital Use In New York City.** Primeiro artigo a citar o termo ambulatory-care sensitive conditions [John Billings, Lisa Zeitel, Joanne Lukomnik, Timothy S. Carey, Arthur E. Blank, and Laurie Newman](https://www.healthaffairs.org/doi/pdf/10.1377/hlthaff.12.1.162){target="_blank"} 


- **Internações por condições sensíveis à atenção primária: a construção da lista brasileira como ferramenta para medir o desempenho do sistema de saúde (Projeto ICSAP – Brasil).** [Cad. Saúde Pública, Rio de Janeiro, 25(6):1337-1349, jun, 2009](http://www.scielo.br/pdf/csp/v25n6/16.pdf){target="_blank"}    

- **The Family Health Strategy: expanding access and reducing hospitalizations due to ambulatory care sensitive conditions (ACSC).** The results show a 45% reduction of the standardized ACSC rates per 10,000 inhabitants, from 120 to 66 in the period 2001-2016.  [DOI: 10.1590/1413-81232018236.05592018](http://www.scielo.br/pdf/csc/v23n6/en_1413-8123-csc-23-06-1903.pdf){target="_blank"}     

- **Trends in hospitalizations for primary care sensitive conditions following the implementation of Family Health Teams in Belo Horizonte, Brazil.** Sensitive conditions accounted for 115,340 (26.4%) hospitalizations. Over the 4-year period, hospitalizations for sensitive conditions declined by 17.9%, vs only 8.3% for non-sensitive ones (P<0.001). Hospitalization for sensitive conditions declined 22% for women in areas of high social vulnerability vs 9% for women in areas of low vulnerability (P<0.001); for men, 17% vs 10% (P=0.11). [Claunara Schilling Mendonça, Erno Harzheim, Bruce B Duncan, Luciana Neves Nunes, Werner Leyh](https://academic.oup.com/heapol/article/27/4/348/605470){target="_blank"}   


- **Internações por condições sensíveis à atenção primária à saúde, 2008-2015: uma análise do impacto da expansão da ESF na cidade do Rio de Janeiro.** [Cad. saúde colet. vol.26 no.2 Rio de Janeiro abr./jun. 2018](http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1414-462X2018000200178&lng=pt&nrm=iso&tlng=pt){target="_blank"}       
Identificou-se tendência ao aumento da cobertura da ESF e à redução dos indicadores de ICSAP, bem como correlação inversa entre a cobertura pela ESF e a proporção de ICSAP (r = -0,888, p = 0,020), e entre a cobertura pela ESF e a taxa de ICSAP (r = -0,753, p = 0,031). Observou-se associação significativa para as razões de taxa dos indicadores de cobertura a partir de 2011 e de taxas de internação a partir de 2013.   
Cad. saúde colet. vol.26 no.2 Rio de Janeiro abr./jun. 2018 http://dx.doi.org/10.1590/1414-462x201800020230    


- **Hospitalizations for ambulatory care sensitive conditions as an indicator of access to primary care and excess of bed supply.** ACSC hospitalization, while being a negative index of primary care access, can also be a measure indicating the impact of the hospital bed supply, and it is still a valid measure of the disparity of health care, the original motivation for this topic. [BMC Health Services Research volume 19, Article number: 259 (2019)](https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-019-4098-x){target="_blank"}   


- **The impact of the Brazilian family health strategy on selected primary care sensitive conditions: A systematic review.** Among these ecological studies with limited quality evidence, increasing coverage by the FHS was consistently associated with improvements in child mortality. Scarce evidence on other health outcomes, hospitalization and synergies with cash transfer was found. [.Bastos ML, Menzies D, Hone T, Dehghani K, Trajman A (2017) PLOS ONE 12(12): e0189557.](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0182336){target="_blank"}    


## Priority setting {-}  


- **Stakeholder involvement in health research priority setting in low income countries: the case of Zambia.** [Lydia Kapiriri; Research Involvement and Engagement (2018) 4:41](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6234591/pdf/40900_2018_Article_121.pdf){target="_blank"}     

- **Priority-setting in public health research funding organisations: an exploratory qualitative study among five high-profile funders.** Priority-setting for strategic funding programmes in public health research involves consultation mainly with researchers in the early phase of the process. There is an opportunity for greater breadth of participation and more transparency in priority-setting mechanisms for strategic funding programmes in population and public health research. [Health Res Policy Syst. 2018; 16: 53. Published online 2018 Jun 22. doi: 10.1186/s12961-018-0335-8](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6014000/){target="_blank"}     

- **Past, present and future challenges in health care priority setting.** [J Health Organ Manag. 2018 May 21;32(3):444-462. doi: 10.1108/JHOM-01-2018-0005](https://www.ncbi.nlm.nih.gov/pubmed/29771204){target="_blank"}     

- **Applying priority-setting frameworks: A review of public and vulnerable populations' participation in health-system priority setting.** [Health Policy. 2019 Dec 19. pii: S0168-8510(19)30299-4. doi: 10.1016/j.healthpol.2019.12.005](https://www.ncbi.nlm.nih.gov/pubmed/31874742){target="_blank"}     


- **Priority setting in health policy in Sweden and a comparison with Norway.** [Johan Calltorp; Health Policy 50 (1999) 1–22](http://www.medicine.mcgill.ca/epidemiology/courses/EPIB654/Summer2010/Policy/Health%20policy%20-%20Sweden%20-%20compare%20w-Norway.pdf){target="_blank"}     



## Cash transfer programs {-}   


- **Effect of a conditional cash transfer programme on childhood mortality: a nationwide analysis of Brazilian municipalities** [Rasella, D., Aquino, R., Santos, C. A., Paes-Sousa, R., & Barreto, M. L. (2013). The Lancet, 382(9886), 57–64. doi:10.1016/s0140-6736(13)60715-1](https://sci-hub.tw/https://doi.org/10.1016/S0140-6736(13)60715-1){target="_blank"}    






- **The combined effects of the expansion of primary health care and conditional cash transfers on infant mortality in Brazil, 1998-2010.** The association of higher FHP coverage with lower PNIM became stronger as BFP coverage increased. At the means of all other variables, when BFP coverage was 25%, predicted PNIM was 5.24 (95% confidence interval [CI] = 4.95, 5.53) for FHP coverage = 0% and 3.54 (95% CI = 2.77, 4.31) for FHP coverage = 100%. When BFP coverage was 60%, predicted PNIM was 4.65 (95% CI = 4.36, 4.94) when FHP coverage = 0% and 1.38 (95% CI = 0.88, 1.89) when FHP coverage = 100%. [American Journal of Public Health | November 2013, Vol 103, No. 11](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3828713/pdf/AJPH.2013.301452.pdf){target="_blank"}    


## Multimorbidity {-}  

- **Epidemiology of multimorbidity within the Brazilian adult general population: Evidence from the 2013 National Health Survey (PNS 2013).** Multimorbidity in Brazil is as common as in more affluent countries. Women in Brazil develop diseases at younger ages than men. [Magdalena Rzewuska ,João Mazzoncini de Azevedo-Marques, Domenica Coxon, Maria Lúcia Zanetti, Ana Carolina Guidorizzi Zanetti, Laercio Joel Franco, Jair Lício Ferreira Santos Published: February 9, 2017 https://doi.org/10.1371/journal.pone.0171813](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0171813){target="_blank"}    


- **Multimorbidity, functional limitations, and outcomes: Interactions in a population-based cohort of older adults.** Among 13,145 persons, 34% had neither multimorbidity nor functional limitations, 44% had multimorbidity only, 4% had functional limitations only, and 18% had both. Over a median follow-up of 11 years, 5906 ED visits, 2654 hospitalizations, and 4559 deaths occurred. Synergistic interactions on an additive scale of multimorbidity and functional limitations were observed for all outcomes; however, the magnitude of the interactions decreased with advancing age. The HR (95% confidence interval) for death among persons with both multimorbidity and functional limitations was 5.34 (4.40–6.47) at age 60–69, 4.16 (3.59–4.83) at age 70–79, and 2.86 (2.45–3.35) at age 80–89 years. [Journal of Comorbidity Volume 9: 1–9](https://journals.sagepub.com/doi/pdf/10.1177/2235042X19873486){target="_blank"}    


## Clinical governance and Sustainability {-}    


- **What is clinical governance?** Clinical governance is defined as “A framework through which NHS organisations are accountable for continuously improving the quality of their services and safe-guarding high standards of care by creating an environment in which excellence in clinical care will flourish.”1 It's often thought of in terms of the seven pillars of clinical governance—clinical effectiveness, risk management, patient experience and involvement, communication, resource effectiveness, strategic effectiveness, and learning effectiveness. [Carl Gray; BMJ 2005; 330 doi: https://doi.org/10.1136/bmj.330.7506.s254-b BMJ 2005;330:s254](https://www.bmj.com/content/330/7506/s254.3){target="_blank"}   


- **Clinical governance and the drive for quality improvement in the new NHS in England.** [Look at page 25](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1113460/pdf/61.pdf){target="_blank"}     


- **Strategies for developing sustainable health research capacity in low and middle-income countries: a prospective, qualitative study investigating the barriers and enablers to locally led clinical trial conduct in Ethiopia, Cameroon and Sri Lanka.** [Samuel R P Franzen, Clare Chandler, Sisira Siribaddana, Julius Atashili, Brian Angus, Trudie Lang; BMJ Open 2017;7:e017246. doi:10.1136/bmjopen-2017-017246](https://bmjopen.bmj.com/content/bmjopen/7/10/e017246.full.pdf){target="_blank"}    


- **Accountability for clinical governance: developing collective responsibility for quality in primary care.** Clinical governance in primary care is aimed at enhancing the collective responsibility and accountability of professionals in primary care groups or trusts. [Pauline Allen; BMJ 2000;321:608–11](https://www.who.int/management/partnerships/accountability/ClinicalGovernancePHCAccountability.pdf){target="_blank"}    


- **Is Management Essential to Improving the Performance and Sustainability of Health Care Systems and Organizations? A Systematic Review and a Roadmap for Future Studies Review of Literature.** Performance of health care systems and organizations seems to be correlated with management practices, leadership, manager characteristics, and cultural attributes that are associated with managerial values and approaches. [VALUE IN HEALTH 16 (2013) S46–S51](https://www.valueinhealthjournal.com/article/S1098-3015(12)04155-1/pdf){target="_blank"}     
 

## Quality Improvement initiatives {-}  


- **Quality and Outcomes Framework: what have we learnt?** [BMJ 2016;354:i4060 doi: 10.1136/bmj.i4060](https://www.bmj.com/content/bmj/354/bmj.i4060.full.pdf){target="_blank"}     

- **Definition, structure, content, use and impacts of electronic health records: a review of the research literature.** The aspects of information quality most often explored in the studies reviewed were the completeness and accuracy of different data components. It has been shown in several studies that the use of an information system was conducive to more complete and accurate documentation by health care professionals. The quality of information is particularly important in patient care, but EHRs also provide important information for secondary purposes, such as health policy planning. [Int J Med Inform. 2008 May;77(5):291-304. Epub 2007 Oct 22](https://sci-hub.tw/10.1016/j.ijmedinf.2007.09.001){target="_blank"}     

- **Do electronic medical records improve quality of care?** [Manca, Donna P & Greiver, Michelle](Canadian Family Physician • Le Médecin de famille canadien | Vol 61: october • octobre 2015){target="_blank"}    


- **Developing Quality and Outcomes Framework (QOF) indicators and the concept of 'QOFability'** [Lester, H. Campbell, Stephen, Quality in Primary Care](http://primarycare.imedpub.com/developing-quality-and-outcomes-framework-qof-indicators-and-the-concept-of-qofability.php?aid=902){target="_blank"}    


- **The Quality and Outcomes Framework: Body commodification in UK general practice** [Norman, Armando H. Russell, Andrew J. Merli, Claudia; Social Science & Medicine (2016)](https://sci-hub.tw/10.1016/j.socscimed.2016.10.009){target="_blank"}    


- **Effects of PACK guide training on the management of asthma and chronic obstructive pulmonary disease by primary care clinicians: a pragmatic cluster randomised controlled trial in Florianópolis, Brazil.** [Max Oscar Bachmann, Eric D Bateman, Rafael Stelmach, Alvaro A Cruz, Matheus Pacheco de Andrade, Ronaldo Zonta, Jorge Zepeda, Sonia Natal, Ruth Vania Cornick, Camilla Wattrus, Lauren Anderson, Daniella Georgeu-Pepper, Carl Lombard, Lara R Fairall; BMJ Global Health 2019;4:e001921. doi:10.1136/bmjgh-2019-001921](file:///C:/Users/Adelson/Downloads/e001921.full.pdf){target="_blank"}    


## Research in Primary Care {-}  

- **Data Resource Profile: National electronic medical record data from the Canadian Primary Care Sentinel Surveillance Network (CPCSSN)** [International Journal of Epidemiology, 2017, 1091–1092f, doi: 10.1093/ije/dyw248](https://sci-hub.tw/10.1093/ije/dyw248){target="_blank"}    


- **Participatory governance over research in an academic research network: the case of Diabetes Action Canada** [Willison DJ, et al. BMJ Open 2019;9:e026828. doi:10.1136/bmjopen-2018-026828](https://bmjopen.bmj.com/content/bmjopen/9/4/e026828.full.pdf){target="_blank"}    


- **The World Health Report 2013: Research for Universal Health Coverage** [Christopher Dye, Ties Boerma, David Evans, Anthony Harries, Christian Lienhardt, Joanne McManus, Tikki Pang, Robert Terry, Rony Zachariah](https://www.researchgate.net/publication/259864310_The_World_Health_Report_2013_research_for_universal_health_coverage_World_Health_Organization_contributor_2013_ISBN_9789241564595_Available_from_httpappswhointirisbitstream106658576129789240690837_eng){target="_blank"}    

- **Unfinished Business: The Role of Research in Family Medicine** [ANNALS OF FAMILY MEDICINE ✦ WWW.ANNFAMMED.ORG ✦ VOL. 17, NO. 1 ✦ JANUARY/FEBRUARY 2019](http://www.annfammed.org/content/17/1/70.full.pdf+html){target="_blank"}    

- **The need for research in primary care** [De Maeseneer, J. M., van Driel, M. L., Green, L. A., & van Weel, C. (2003). The Lancet, 362(9392), 1314–1319. doi:10.1016/s0140-6736(03)14576-x](https://sci-hub.tw/https://doi.org/10.1016/S0140-6736(03)14576-X){target="_blank"}    

- **Integração Ensino, Pesquisa e Serviços em Saúde: antecedentes, estratégias e iniciativas** [Saúde Soc. São Paulo, v.22, n.1, p.187-198, 2013](http://www.scielo.br/pdf/sausoc/v22n1/17.pdf){target="_blank"}    


## DATABASES {-}  


- **Manual SAIH - ** [manual_sih_janeiro_2017.pdf](http://www.saude.sp.gov.br/resources/ses/perfil/gestor/homepage/auditoria/manuais/manual_sih_janeiro_2017.pdf){target="_blank"}    


- **Privacy protection and public goods: building a genetic database for health research in Newfoundland and Labrador** [J Am Med Inform Assoc. 2013 Jan-Feb; 20(1): 38–43. doi: 10.1136/amiajnl-2012-001009](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3555321/){target="_blank"}    


- **The Information Governance Review.** Information: To share or not to share? The Information Governance Review; March 2013. We recommend that the linkage of de-identified but still potentially identifiable information from more than one organisation should be done in specialist, well-governed, independently scrutinised environments known as ‘accredited safe havens’. Chapter 6 proposes national minimum standards for safe havens, supported by a system of external independent audit and other requirements to give the public confidence. [The Information Governance Review](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/192572/2900774_InfoGovernance_accv2.pdf){target="_blank"}     


- **Making sense of big data in health research: Towards an EU action plan.** The potential of “big data” for improving health is enormous but, at the same time, we face a wide range of challenges to overcome urgently. There is a lack of harmonization of data formats, processing, analysis, and data transfer, which leads to incompatibilities and lost opportunities. Legal frameworks for data sharing are evolving. Clinicians, researchers, and citizens need improved methods, tools, and training to generate, analyze, and query data effectively [Auffray et al. Genome Medicine (2016) 8:71 DOI 10.1186/s13073-016-0323-y](https://genomemedicine.biomedcentral.com/track/pdf/10.1186/s13073-016-0323-y){target="_blank"}    


- **Researcher guide: requesting outputs from Safe Haven and disclosure control.** [isdscotland](https://www.isdscotland.org/Products-and-Services/EDRIS/_docs/Researcher-guide-to-disclosure-control-V1-2.pdf){target="_blank"}     

- **Linking and sharing routine health data for research in England.** Policy recommendations: (1) Establish systems and incentives to encourage secure data linkage and sharing for research in
England; (2) Increase capacity for data linkage and sharing by public organisations; (3) Streamline procedures to enable appropriate and efficient access to routine health data for research; (4) Improve transparency and communication around routine health data access and use between data provider organisations and researchers; (5) Provide better support for researchers working with routine health data - See page 18 for the detailed policy recommendations. [Linking and sharing routine health data for research in England, PHG Foundation (2017); ISBN 978-1-907198-27-4](https://www.phgfoundation.org/documents/PHGF-linking-and-sharing-routine-health-data-for-research-in-england.pdf){target="_blank"}    

- **Challenges in administrative data linkage for research.** We aim to increase understanding of the implications of (i) the data linkage environment and privacy preservation; (ii) the linkage process itself (including data preparation, and deterministic and probabilistic linkage methods) and (iii) linkage quality and potential bias in linked data. [Katie Harron, Chris Dibben, James Boyd, Anders Hjern, Mahmoud Azimaee, Mauricio L Barreto, Harvey Goldstein; Big Data & Society; July–December 2017: 1–12](https://journals.sagepub.com/doi/pdf/10.1177/2053951717745678){target="_blank"}     


- **A decade of data linkage in Western Australia: strategic design, applications and benefits of the WA data linkage system** [Aust Health Rev 2008: 32(4): 766–777](http://www.publish.csiro.au/ah/pdf/AH080766){target="_blank"}     


- **History of the Rochester Epidemiology Project: Half a Century of Medical Records Linkage in a US Population** [Rocca, W. A., Yawn, B. P., St. Sauver, J. L., Grossardt, B. R., & Melton, L. J. (2012). Mayo Clinic Proceedings, 87(12), 1202–1213. doi:10.1016/j.mayocp.2012.08.012](https://sci-hub.tw/10.1016/j.mayocp.2012.08.012){target="_blank"}      


- **Observations Made Upon the Bills of Mortality.** John Graunt’s Observations Made Upon the Bills of Mortality inaugurated a new approach to health issues: the reliance on evidence versus belief. [Morabia, A.; BMJ, 346(jan07 4), e8640–e8640. doi:10.1136/bmj.e8640](https://sci-hub.tw/10.1136/bmj.e8640){target="_blank"}      


- **Sistemas Nacionais de Informação e levantamentos populacionais: algumas contribuições do Ministério da Saúde e do IBGE para a análise das capitais brasileiras nos últimos 30 anos** [Luiz Felipe Pinto, Marcos Paulo Soares de Freitas, André William Sant’Anna de Figueiredo; Ciência & Saúde Coletiva, 23(6):1859-1870, 2018 DOI: 10.1590/1413-81232018236.05072018](http://www.scielo.br/pdf/csc/v23n6/1413-8123-csc-23-06-1859.pdf){target="_blank"}      


- **Rede Nacional de Dados em Saúde - ** [RNDS](http://datasus.saude.gov.br/uncategorized/ministerio-da-saude-lanca-a-rede-nacional-de-dados-em-saude-e-datasus-realiza-encontro-tecnico/){target="_blank"} Seu principal objetivo é promover a troca de informações entre os pontos da Rede de Atenção à Saúde, permitindo a transição e continuidade do cuidado nos setores público e privado.   


- **Rede Interagencial de Informações para a Saúde (Ripsa).** A Rede Interagencial de Informações para a Saúde (RIPSA) vem publicando desde 1995 uma série de recomendações e Manuais. Sua maior limitação se refere ao fato de que as unidades de análise dos indicadores propostos nem sempre correspondem à esfera municipal [RIPSA, 1996](http://www.ripsa.org.br/vhl/metodologia-ripsa/concepcao-e-estruturacao/){target="_blank"}     


- **GESTÃO DA SAÚDE: O USO DOS SISTEMAS DE INFORMAÇÃO E O COMPARTILHAMENTO DE CONHECIMENTO PARA A TOMADA DE DECISÃO.** Os gestores ainda são neófitos no uso dos Sistemas de Informação em Saúde; há envolvimento de atores na decisão, porém em alguns casos não há efetiva participação social; ocorre pouca qualificação em Sistema de Informação em Saúde; gestões implementam inovação, embora incipiente; há dificuldade quando da implantação de sistema novo e acesso à internet. [Alba Lúcia Santos Pinheiro, Kerlly Taynara Santos Andrade, Dejeane de Oliveira Silva, Fabiana Costa, Machado Zacharias, Mariana Figueiredo Souza Gomide, Ione Carvalho Pinto](http://www.scielo.br/pdf/tce/v25n3/pt_0104-0707-tce-25-03-3440015.pdf){target="_blank"}     


- **O SUS, o DATASUS e a informação em saúde: uma proposta de gestão participativa.** [Lygia Helena Valle da Costa Ferraz](https://bvssp.icict.fiocruz.br/pdf/25885_ferrazlhvcm.pdf){target="_blank"}     


- **Studies in Health Technology and Informatics.** Série de artigos sobre informática e saúde. [Volume 216](http://ebooks.iospress.nl/publication/40579){target="_blank"}     


- **Administrative Database Studies: Goldmine or Goose Chase?** Administrative data provide researchers with relatively inexpensive access to large numbers of patients nationwide and are increasingly being used for epidemiological, effectiveness, and safety outcomes studies. Publically available databases from sources such as the NIS and CMS provide information on large proportions of medical visits in the United States, and provide a good source of “real-world” health care data for reliably reported data. However, because administrative data are primarily gathered for billing purposes rather than research purposes, there are several limitations that must be considered, including the potential for inaccuracy and bias. As for all study types, critical appraisal of administrative database studies are critical to avoid arriving at inaccurate conclusions. [Evid Based Spine Care J. 2014 Oct; 5(2): 74–76. doi: 10.1055/s-0034-1390027](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4174180/pdf/10-1055-s-0034-1390027.pdf){target="_blank"}     


- **A Spark-based workflow for probabilistic record linkage of healthcare data.** Description of the making of the 100 million cohort dataset [Workshop Proceedings of the EDBT/ICDT 2015 Joint Conference (March 27, 2015, Brussels, Belgium) on CEURWS.org (ISSN 1613-0073)](http://ceur-ws.org/Vol-1330/paper-04.pdf){target="_blank"}      


- **Why Doctors Hate Their Computers?** Digitization promises to make medical care easier and more efficient. But are screens coming between doctors and patients? [Annals of Medicine - November 12, 2018 Issue, by Atul Gawande](https://www.newyorker.com/magazine/2018/11/12/why-doctors-hate-their-computers){target="_blank"}      


- **Utilização do e-SUS AB e fatores associados ao registro de procedimentos e consultas da atenção básica nos municípios brasileiros.** [Thum, Moara Ailane; Baldisserotto, Julio; Celeste, Roger Keller; Cadernos de Saúde Pública (2019)](http://www.scielo.br/pdf/csp/v35n2/1678-4464-csp-35-02-e00029418.pdf){target="_blank"}      


- **Primary care research network progress in Scotland.** [Frank Sullivan, Alison Hinds, Marie Pitkethly, Shaun Treweek, Philip Wilson & Sally Wyke](https://www.tandfonline.com/doi/pdf/10.3109/13814788.2013.879116?needAccess=true){target="_blank"}      


- **Towards an institute for patient-led research** [Trish Greenhalgh](https://blogs.bmj.com/bmj/2019/11/12/trisha-greenhalgh-towards-an-institute-for-patient-led-research/){target="_blank"}      

- **Diffusion of the e-SUS Primary Care innovation in Family Health Teams.** [Silva TIM, Cavalcante RB, Santos RC, Gontijo TL Guimarães EAA, Oliveira VC. Rev Bras Enferm. (2018);71(6):2945-52.](http://www.scielo.br/pdf/reben/v71n6/0034-7167-reben-71-06-2945.pdf){target="_blank"}      



*
*
*
